# Generated by Django 5.2.7 on 2025-10-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarriorClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('profession', models.CharField(max_length=64)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('move1', models.CharField(max_length=64)),
                ('move2', models.CharField(max_length=64)),
                ('move3', models.CharField(max_length=64)),
                ('move4', models.CharField(max_length=64)),
            ],
        ),
    ]
